export default {
  "login": "suprabhat25",
  "id": 47072868,
  "node_id": "MDQ6VXNlcjQ3MDcyODY4",
  "avatar_url": "https://avatars3.githubusercontent.com/u/47072868?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/suprabhat25",
  "html_url": "https://github.com/suprabhat25",
  "followers_url": "https://api.github.com/users/suprabhat25/followers",
  "following_url": "https://api.github.com/users/suprabhat25/following{/other_user}",
  "gists_url": "https://api.github.com/users/suprabhat25/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/suprabhat25/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/suprabhat25/subscriptions",
  "organizations_url": "https://api.github.com/users/suprabhat25/orgs",
  "repos_url": "https://api.github.com/users/suprabhat25/repos",
  "events_url": "https://api.github.com/users/suprabhat25/events{/privacy}",
  "received_events_url": "https://api.github.com/users/suprabhat25/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Suprabhat Kumar",
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 59,
  "public_gists": 5,
  "followers": 0,
  "following": 12,
  "created_at": "2019-01-27T04:43:07Z",
  "updated_at": "2020-12-31T07:09:07Z"
  }